=== huxiangrui/WebChatOn/WebRoot/user/Claim/Claims.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Claims">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Claim" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="currentDate" type="xs:string"/>
							<xs:element name="serviceDate" type="xs:string"/>
							<xs:element name="providerNumber">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="9"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="memberNumber">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="9"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="serviceCode">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="note">
							<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="100"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== huxiangrui/WebChatOn/WebRoot/user/Claim/Claims.xml
<?xml version="1.0" encoding="utf-8"?>

<Claims xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Claims.xsd">  
  <Claim> 
    <currentDate>05-28-2017 14-36-09</currentDate>  
    <serviceDate>05-28-2017</serviceDate>  
    <providerNumber>000000001</providerNumber>  
    <memberNumber>111111111</memberNumber>  
    <serviceCode>121121</serviceCode>  
    <note>a</note> 
  </Claim>  
  <Claim> 
    <currentDate>06-01-2017 23-08-14</currentDate>  
    <serviceDate>01-12-2017</serviceDate>  
    <providerNumber>000000001</providerNumber>  
    <memberNumber>111111111</memberNumber>  
    <serviceCode>121121</serviceCode>  
    <note/> 
  </Claim>  
  <Claim>
    <currentDate>06-04-2017 15-27-02</currentDate>
    <serviceDate>04-11-2017</serviceDate>
    <providerNumber>000000001</providerNumber>
    <memberNumber>111111111</memberNumber>
    <serviceCode>121121</serviceCode>
    <note></note>
  </Claim>
</Claims>
