=== huxiangrui/WebChatOn/WebRoot/user/Provider/Providers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Providers">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="Provider">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="25"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="address">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="25"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="city">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="14"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="country">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="zip">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="5"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="I"/>
										<xs:pattern value="D"/>
										<xs:pattern value="E"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="number" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:length value="9"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== huxiangrui/WebChatOn/WebRoot/user/Provider/Providers.xml
<?xml version="1.0" encoding="utf-8"?>

<Providers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Providers.xsd">  
  <Provider number="000000001"> 
    <name>Tom</name>  
    <address>aa</address>  
    <city>WuHan</city>  
    <country>C</country>  
    <zip>12111</zip>  
    <email>121@qq.com</email>  
    <type>I</type> 
  </Provider>  
  <Provider number="111111111">
    <name>Anny</name>
    <address>aa</address>
    <city>aa</city>
    <country>aa</country>
    <zip>12345</zip>
    <email>11@qq.com</email>
    <type>E</type>
  </Provider>
</Providers>
